research_task:
  description: >
    Conduct a thorough research about {topic}
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  # agent: researcher

reporting_task:
  description: >
    Review the topic into a full section for a report.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
  # agent: reporting_analyst
  output_file: report.md
